apiVersion: 1
datasources:
  - name: DS_INFLUXDB
    type: influxdb
    access: proxy
    isDefault: true
    editable: true
    url: ${INFLUX_URL}
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
